# Generated by Django 2.2.5 on 2019-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='books')),
                ('data_of_production', models.DateField()),
                ('category', models.CharField(choices=[('sci_fi', 'SCI_FI'), ('horror', 'HORROR'), ('thrillers', 'THRILLERS'), ('romance', 'ROMANCE'), ('biographies', 'BIOGRAPHIES'), ('fantasty', 'FANTASY')], max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('main_heroes', models.CharField(max_length=200)),
                ('name_series', models.CharField(max_length=100)),
                ('film_adaptation', models.BooleanField(default=False)),
                ('movie_trailer', models.URLField()),
                ('tags', models.CharField(max_length=100)),
                ('views_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
