# Generated by Django 2.2.5 on 2019-09-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='authors')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='books')),
                ('data_of_production', models.DateField()),
                ('category', models.CharField(choices=[('horror', 'HORROR'), ('romance', 'ROMANCE'), ('sci_fi', 'SCI_FI'), ('thrillers', 'THRILLER'), ('biographies', 'BIOGRAPHIES'), ('fantasy', 'FANTASY')], max_length=15)),
                ('description', models.TextField(max_length=1000)),
                ('main_characters', models.CharField(max_length=200)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('film_adaptation', models.BooleanField(default=False)),
                ('movie_trailer', models.URLField(blank=True)),
                ('tags', models.CharField(max_length=100)),
                ('views_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
            ],
        ),
    ]
