# Generated by Django 2.2.5 on 2019-09-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('romance', 'ROMANCE'), ('thrillers', 'THRILLERS'), ('sci_fi', 'SCI_FI'), ('biographies', 'BIOGRAPHIES'), ('horror', 'HORROR'), ('fantasty', 'FANTASY')], max_length=15),
        ),
    ]
