# Generated by Django 2.2.5 on 2019-09-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190918_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'FANTASY'), ('sci_fi', 'SCI_FI'), ('biographies', 'BIOGRAPHIES'), ('romance', 'ROMANCE'), ('horror', 'HORROR'), ('thrillers', 'THRILLER')], max_length=15),
        ),
    ]
