# Generated by Django 2.2.5 on 2019-09-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20190907_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='main_heroes',
            new_name='main_characters',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasty', 'FANTASY'), ('thrillers', 'THRILLERS'), ('sci_fi', 'SCI_FI'), ('biographies', 'BIOGRAPHIES'), ('romance', 'ROMANCE'), ('horror', 'HORROR')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='movie_trailer',
            field=models.URLField(default=None),
        ),
    ]
