# Generated by Django 2.2.5 on 2019-09-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190907_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('thrillers', 'THRILLERS'), ('romance', 'ROMANCE'), ('horror', 'HORROR'), ('sci_fi', 'SCI_FI'), ('biographies', 'BIOGRAPHIES'), ('fantasty', 'FANTASY')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='movie_trailer',
            field=models.URLField(blank=True),
        ),
    ]
