# Generated by Django 2.2.5 on 2019-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190907_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('horror', 'HORROR'), ('thrillers', 'THRILLERS'), ('sci_fi', 'SCI_FI'), ('romance', 'ROMANCE'), ('fantasty', 'FANTASY'), ('biographies', 'BIOGRAPHIES')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='name_series',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
