# Generated by Django 2.2.5 on 2019-09-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190907_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('biographies', 'BIOGRAPHIES'), ('thrillers', 'THRILLERS'), ('sci_fi', 'SCI_FI'), ('horror', 'HORROR'), ('fantasty', 'FANTASY'), ('romance', 'ROMANCE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
