# Generated by Django 2.2.5 on 2019-09-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190911_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('biographies', 'BIOGRAPHIES'), ('romance', 'ROMANCE'), ('thriller', 'THRILLER'), ('fantasy', 'FANTASY'), ('sci_fi', 'SCI_FI'), ('horror', 'HORROR')], max_length=15),
        ),
    ]
