# Generated by Django 2.2.5 on 2019-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fantasy', 'FANTASY'), ('biographies', 'BIOGRAPHIES'), ('horror', 'HORROR'), ('thrillers', 'THRILLER'), ('sci_fi', 'SCI_FI'), ('romance', 'ROMANCE')], max_length=15),
        ),
    ]
