# Generated by Django 2.2.5 on 2019-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190919_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('thrillers', 'THRILLER'), ('fantasy', 'FANTASY'), ('biographies', 'BIOGRAPHIES'), ('horror', 'HORROR'), ('romance', 'ROMANCE'), ('sci_fi', 'SCI_FI')], max_length=15),
        ),
    ]
